# Generated by Django 3.2.5 on 2021-07-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cip', models.FloatField()),
                ('degree_type_id', models.IntegerField()),
                ('median_salary', models.FloatField()),
                ('num_observations', models.IntegerField(null=True)),
                ('school_id', models.IntegerField()),
            ],
        ),
    ]
